services:
  backend-database:
    container_name: backend-database
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mouts
    networks:
      - application
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./data/backend-database:/var/lib/postgresql/data

  redis:
    container_name: backend-cache-redis
    image: redis:7.2.4
    command: redis-server --requirepass dY5MRW2^!jxHX
    ports:
      - 6379:6379
    restart: always
    networks:
      - application

 

networks:
  application:
  sonarnet:

volumes:
  postgresql:
  postgresql_data:
