services:
  backend-database:
    container_name: backend-database
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mouts
    networks:
      - application
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./data/backend-database:/var/lib/postgresql/data

  redis:
    container_name: backend-cache-redis
    image: redis:7.2.4
    command: redis-server --requirepass dY5MRW2^!jxHX
    ports:
      - 6379:6379
    restart: always
    networks:
      - application

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    restart: always
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar-db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    depends_on:
      - sonar-db
    networks:
      - sonarnet

  sonar-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    networks:
      - sonarnet
    restart: always
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

networks:
  application:
  sonarnet:

volumes:
  postgresql:
  postgresql_data:
